import type { Metadata } from "next";
import "./globals.css";
import { PropertyProvider } from "@/features/property/context/use-property";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-sans antialiased">
        <PropertyProvider>
          {children}
        </PropertyProvider>
        </body>
    </html>
  );
}
